services:
  postgres:
    image: postgres:16-alpine
    container_name: f1friends_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: f1friends
      POSTGRES_PASSWORD: f1friends
      POSTGRES_DB: f1friends
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
